# -*- coding: utf-8 -*-
# vim: ft=yaml
---
FreeBSD:
  # https://reviews.freebsd.org/D21570
  pkg:
    deps:
      - devel/py-pip

CentOS:
  pkg:
    deps:
      - iptables
      - procps
      - yum-utils
    docker:
      repo:
        baseurl: 'https://download.docker.com/linux/centos/{{ grains.get('osmajorrelease', '') }}/$basearch/stable'
        gpgkey: 'https://download.docker.com/linux/centos/gpg'

CentOS Stream:
  pkg:
    deps:
      - iptables
      - python3-dnf-plugin-versionlock
      - python3-docker
    docker:
      repo:
        baseurl: 'https://download.docker.com/linux/centos/{{ grains.get('osmajorrelease', '') }}/$basearch/stable'
        gpgkey: 'https://download.docker.com/linux/centos/gpg'

AlmaLinux:
  pkg:
    deps:
      - iptables
      - python3-dnf-plugin-versionlock
      - python3-docker
    docker:
      repo:
        baseurl: 'https://download.docker.com/linux/centos/{{ grains.get('osmajorrelease', '') }}/$basearch/stable'
        file: '/etc/yum.repos.d/docker-ce.repo'
        gpgkey: 'https://download.docker.com/linux/centos/gpg'

Rocky:
  pkg:
    deps:
      - iptables
      - python3-dnf-plugin-versionlock
      - python3-docker
    docker:
      repo:
        baseurl: 'https://download.docker.com/linux/centos/{{ grains.get('osmajorrelease', '') }}/$basearch/stable'
        file: '/etc/yum.repos.d/docker-ce.repo'
        gpgkey: 'https://download.docker.com/linux/centos/gpg'

OEL:
  pkg:
    docker:
      repo:
        baseurl: 'https://download.docker.com/linux/centos/{{ grains.get('osmajorrelease', '') }}/$basearch/stable'
        file: '/etc/yum.repos.d/docker-ce.repo'
        gpgkey: 'https://download.docker.com/linux/centos/gpg'

Raspbian:
  pkg:
    docker:
      repo:
                {%- if 'oscodename' in grains %}
        name: deb [arch=armhf] https://download.docker.com/linux/{{ grains.os|lower }} {{ grains.oscodename }} stable
                {%- endif %}
        file: /etc/apt/sources.list.d/docker.list
        gpgkey: "https://download.docker.com/linux/{{ grains.os|lower }}/gpg"


    compose:
      name: docker-compose
      use_upstream: package

Amazon:
  pkg:
    docker:
      repo:
        baseurl: 'https://download.docker.com/linux/centos/7/$basearch/stable'
        file: '/etc/yum.repos.d/docker-ce.repo'
        gpgkey: 'https://download.docker.com/linux/centos/gpg'

Fedora:
  pkg:
    deps:
      - selinux-policy-minimum
      - python3-dnf-plugin-versionlock
      - python3-docker
    docker:
      repo:
        baseurl: 'https://download.docker.com/linux/fedora/$releasever/$basearch/stable'
        file: '/etc/yum.repos.d/docker-ce.repo'
        gpgkey: 'https://download.docker.com/linux/fedora/gpg'
