# -*- coding: utf-8 -*-
# vim: ft=yaml
---
name: 'Kitchen (Linux)'
'on': ['push', 'pull_request']

jobs:
  kitchen:
    runs-on: 'ubuntu-20.04'
    env:
      CHANGE_MINIKUBE_NONE_USER: true
      MINIKUBE_WANTUPDATENOTIFICATION: false
      MINIKUBE_WANTREPORTERRORPROMPT: false
      MINIKUBE_HOME: '$HOME'
      KUBECONFIG: '$HOME/.kube/config'
    strategy:
      fail-fast: false
      matrix:
        instance:
          # - archive-debian-11-tiamat-py3
          # - archive-debian-10-tiamat-py3
          # - archive-debian-9-tiamat-py3
          # - archive-ubuntu-2204-tiamat-py3
          # - archive-ubuntu-2004-tiamat-py3
          # - archive-ubuntu-1804-tiamat-py3
          # - archive-centos-stream8-tiamat-py3
          # - archive-centos-7-tiamat-py3
          # - archive-amazonlinux-2-tiamat-py3
          # - archive-oraclelinux-8-tiamat-py3
          # - archive-oraclelinux-7-tiamat-py3
          # - archive-almalinux-8-tiamat-py3
          # - archive-rockylinux-8-tiamat-py3
          # - archive-debian-11-master-py3
          # - package-debian-11-master-py3
          # - repo-debian-11-master-py3
          # - clean-debian-11-master-py3
          # - composeclean-debian-11-master-py3
          # - dockeronly-debian-11-master-py3
          - debian-11-master-py3
          # - archive-debian-10-master-py3
          # - package-debian-10-master-py3
          # - repo-debian-10-master-py3
          # - composeclean-debian-10-master-py3
          # - dockeronly-debian-10-master-py3
          - debian-10-master-py3
          # - archive-debian-9-master-py3
          # - package-debian-9-master-py3
          # - repo-debian-9-master-py3
          # - clean-debian-9-master-py3
          # - composeclean-debian-9-master-py3
          # - dockeronly-debian-9-master-py3
          - debian-9-master-py3
          # - archive-ubuntu-2204-master-py3
          # - package-ubuntu-2204-master-py3
          # - repo-ubuntu-2204-master-py3
          # - clean-ubuntu-2204-master-py3
          # - composeclean-ubuntu-2204-master-py3
          # - dockeronly-ubuntu-2204-master-py3
          - ubuntu-2204-master-py3
          # - archive-ubuntu-2004-master-py3
          # - package-ubuntu-2004-master-py3
          # - repo-ubuntu-2004-master-py3
          # - clean-ubuntu-2004-master-py3
          # - composeclean-ubuntu-2004-master-py3
          # - dockeronly-ubuntu-2004-master-py3
          - ubuntu-2004-master-py3
          # - archive-ubuntu-1804-master-py3
          # - package-ubuntu-1804-master-py3
          # - repo-ubuntu-1804-master-py3
          # - clean-ubuntu-1804-master-py3
          # - composeclean-ubuntu-1804-master-py3
          # - dockeronly-ubuntu-1804-master-py3
          - ubuntu-1804-master-py3
          # - archive-centos-stream8-master-py3
          # - package-centos-stream8-master-py3
          # - repo-centos-stream8-master-py3
          # - clean-centos-stream8-master-py3
          # - composeclean-centos-stream8-master-py3
          # - dockeronly-centos-stream8-master-py3
          - centos-stream8-master-py3
          # - archive-centos-7-master-py3
          # - package-centos-7-master-py3
          # - repo-centos-7-master-py3
          # - clean-centos-7-master-py3
          # - composeclean-centos-7-master-py3
          # - dockeronly-centos-7-master-py3
          - centos-7-master-py3
          # - archive-fedora-36-master-py3
          # - package-fedora-36-master-py3
          # - repo-fedora-36-master-py3
          # - clean-fedora-36-master-py3
          # - composeclean-fedora-36-master-py3
          # - dockeronly-fedora-36-master-py3
          - fedora-36-master-py3
          # - archive-fedora-35-master-py3
          # - package-fedora-35-master-py3
          # - repo-fedora-35-master-py3
          # - clean-fedora-35-master-py3
          # - composeclean-fedora-35-master-py3
          # - dockeronly-fedora-35-master-py3
          - fedora-35-master-py3
          # - archive-opensuse-leap-153-master-py3
          # - package-opensuse-leap-153-master-py3
          # - repo-opensuse-leap-153-master-py3
          # - clean-opensuse-leap-153-master-py3
          # - composeclean-opensuse-leap-153-master-py3
          # - dockeronly-opensuse-leap-153-master-py3
          # - opensuse-leap-153-master-py3
          # - archive-opensuse-tmbl-latest-master-py3
          # - package-opensuse-tmbl-latest-master-py3
          # - repo-opensuse-tmbl-latest-master-py3
          - clean-opensuse-tmbl-latest-master-py3
          # - composeclean-opensuse-tmbl-latest-master-py3
          # - dockeronly-opensuse-tmbl-latest-master-py3
          # - opensuse-tmbl-latest-master-py3
          - archive-amazonlinux-2-master-py3
          # - package-amazonlinux-2-master-py3
          # - repo-amazonlinux-2-master-py3
          # - clean-amazonlinux-2-master-py3
          # - composeclean-amazonlinux-2-master-py3
          # - dockeronly-amazonlinux-2-master-py3
          # - amazonlinux-2-master-py3
          - archive-oraclelinux-8-master-py3
          # - package-oraclelinux-8-master-py3
          # - repo-oraclelinux-8-master-py3
          # - clean-oraclelinux-8-master-py3
          # - composeclean-oraclelinux-8-master-py3
          # - dockeronly-oraclelinux-8-master-py3
          # - oraclelinux-8-master-py3
          - archive-oraclelinux-7-master-py3
          # - package-oraclelinux-7-master-py3
          # - repo-oraclelinux-7-master-py3
          # - clean-oraclelinux-7-master-py3
          # - composeclean-oraclelinux-7-master-py3
          # - dockeronly-oraclelinux-7-master-py3
          # - oraclelinux-7-master-py3
          # - archive-arch-base-latest-master-py3
          # - package-arch-base-latest-master-py3
          # - clean-arch-base-latest-master-py3
          # - composeclean-arch-base-latest-master-py3
          # - dockeronly-arch-base-latest-master-py3
          - arch-base-latest-master-py3
          # - archive-gentoo-stage3-latest-master-py3
          # - package-gentoo-stage3-latest-master-py3
          # - repo-gentoo-stage3-latest-master-py3
          # - clean-gentoo-stage3-latest-master-py3
          # - composeclean-gentoo-stage3-latest-master-py3
          # - dockeronly-gentoo-stage3-latest-master-py3
          # - gentoo-stage3-latest-master-py3
          - archive-gentoo-stage3-systemd-master-py3
          # - package-gentoo-stage3-systemd-master-py3
          # - repo-gentoo-stage3-systemd-master-py3
          # - clean-gentoo-stage3-systemd-master-py3
          # - composeclean-gentoo-stage3-systemd-master-py3
          # - dockeronly-gentoo-stage3-systemd-master-py3
          # - gentoo-stage3-systemd-master-py3
          # - archive-almalinux-8-master-py3
          # - package-almalinux-8-master-py3
          # - repo-almalinux-8-master-py3
          # - clean-almalinux-8-master-py3
          # - composeclean-almalinux-8-master-py3
          # - dockeronly-almalinux-8-master-py3
          - almalinux-8-master-py3
          # - archive-rockylinux-8-master-py3
          # - package-rockylinux-8-master-py3
          # - repo-rockylinux-8-master-py3
          # - clean-rockylinux-8-master-py3
          # - composeclean-rockylinux-8-master-py3
          # - dockeronly-rockylinux-8-master-py3
          - rockylinux-8-master-py3
          # - archive-debian-11-3004-1-py3
          # - archive-debian-10-3004-1-py3
          # - archive-debian-9-3004-1-py3
          # - archive-ubuntu-2204-3004-1-py3
          # - archive-ubuntu-2004-3004-1-py3
          # - archive-ubuntu-1804-3004-1-py3
          # - archive-centos-stream8-3004-1-py3
          # - archive-centos-7-3004-1-py3
          # - archive-fedora-36-3004-1-py3
          # - archive-fedora-35-3004-1-py3
          # - archive-amazonlinux-2-3004-1-py3
          # - archive-oraclelinux-8-3004-1-py3
          # - archive-oraclelinux-7-3004-1-py3
          # - archive-arch-base-latest-3004-1-py3
          # - archive-gentoo-stage3-latest-3004-1-py3
          # - archive-gentoo-stage3-systemd-3004-1-py3
          # - archive-almalinux-8-3004-1-py3
          # - archive-rockylinux-8-3004-1-py3
          # - archive-opensuse-leap-153-3004-0-py3
          # - archive-opensuse-tmbl-latest-3004-0-py3
          # - archive-debian-10-3003-4-py3
          # - archive-debian-9-3003-4-py3
          # - archive-ubuntu-2004-3003-4-py3
          # - archive-ubuntu-1804-3003-4-py3
          # - archive-centos-stream8-3003-4-py3
          # - archive-centos-7-3003-4-py3
          # - archive-amazonlinux-2-3003-4-py3
          # - archive-oraclelinux-8-3003-4-py3
          # - archive-oraclelinux-7-3003-4-py3
          # - archive-almalinux-8-3003-4-py3
    steps:
      - name: 'Check out code'
        uses: 'actions/checkout@v2'
      - name: 'Set up Bundler cache'
        uses: 'actions/cache@v1'
        with:
          path: 'vendor/bundle'
          key: "${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}"
          restore-keys: "${{ runner.os }}-gems-"
      - name: 'Install Bundler'
        run: |
          sudo gem install bundler \
            -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)" \
            --quiet --no-document
      - name: 'Run Bundler'
        run: |
          ruby --version
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: 'Run Test Kitchen'
        run: 'bundle exec kitchen verify ${{ matrix.instance }}'
        env:
          CHEF_LICENSE: 'accept-no-persist'
